### ISSUE TITLE
gratitude

### ISSUE THREAD

**Issue by zubi45** [riesentoaster/lvls#1]
I've cloned your repo and I'm very surprised what you have achieved in  the mean time. I've overlooked the code and it looks great even though I have no experience in node.js nor java.script
thanks a lot for your work.
I'm currently trying to run the server on a windows machine, is it also possible to run it under Linux or on a raspi?

**Comment by zubi45** [comment]
Had OSB already on my maschine so I startet to run the code. Unfortunately I got the following Error in the shell:
```PowerShell
2019-11-20 19:49:27 4460 [ERROR] Node Media Trans Server startup failed. ffmpeg:/usr/local/bin/ffmpeg cannot be executed.
```
Therefore the client got errors by trying to connect to the server.

And the hole Log below:
```PowerShell
    Directory: C:\Users\Martin Maroni\Documents\#Kreativ\Software\uebersetzungStream\lvls


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       20.11.2019     18:37                public
d-----       20.11.2019     18:37                src
d-----       20.11.2019     18:37                views
-a----       20.11.2019     18:37            184 .gitignore
-a----       20.11.2019     18:37          36143 package-lock.json
-a----       20.11.2019     18:37           1063 package.json
-a----       20.11.2019     18:37           1672 README.md
-a----       20.11.2019     18:37           5992 tsconfig.json


(base) PS C:\Users\Martin Maroni\Documents\#Kreativ\Software\uebersetzungStream\lvls> npm

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    C:\Users\Martin Maroni\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.12.1 C:\Program Files\nodejs\node_modules\npm
(base) PS C:\Users\Martin Maroni\Documents\#Kreativ\Software\uebersetzungStream\lvls> npm install

> ejs@2.7.3 postinstall C:\Users\Martin Maroni\Documents\#Kreativ\Software\uebersetzungStream\lvls\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

added 122 packages from 142 contributors and audited 395 packages in 12.177s
found 0 vulnerabilities

(base) PS C:\Users\Martin Maroni\Documents\#Kreativ\Software\uebersetzungStream\lvls> npm run start

> lvls@1.0.0 start C:\Users\Martin Maroni\Documents\#Kreativ\Software\uebersetzungStream\lvls
> tsc && node dist/app.js

2019-11-20 19:49:27 4460 [INFO] Node Media Server v2.1.4
2019-11-20 19:49:27 4460 [ERROR] Node Media Trans Server startup failed. ffmpeg:/usr/local/bin/ffmpeg cannot be executed.
2019-11-20 19:49:27 4460 [INFO] Node Media Rtmp Server started on port: 1935
2019-11-20 19:49:27 4460 [INFO] Node Media Http Server started on port: 8000
2019-11-20 19:49:27 4460 [INFO] Node Media WebSocket Server started on port: 8000
------------------------------------
URL for OBS: rtmp://192.168.11.1/live, use the desired stream name as the stream key.
URL for clients: http://192.168.11.1:3000/
URL for OBS: rtmp://192.168.226.1/live, use the desired stream name as the stream key.
URL for clients: http://192.168.226.1:3000/
URL for OBS: rtmp://192.168.1.196/live, use the desired stream name as the stream key.
URL for clients: http://192.168.1.196:3000/
------------------------------------
2019-11-20 19:54:56 4460 [INFO] [rtmp connect] id=4BVBJ78W ip=::ffff:192.168.1.196 app=live args={"app":"live","type":"nonprivate","flashVer":"FMLE/3.0 (compatible; FMSc/1.0)","swfUrl":"rtmp://192.168.1.196/live","tcUrl":"rtmp://192.168.1.196/live"}
2019-11-20 19:54:56 4460 [INFO] [rtmp publish] New stream. id=4BVBJ78W streamPath=/live/mytest streamId=1
2019-11-20 19:54:57 4460 [INFO] [rtmp publish] Handle audio. id=4BVBJ78W streamPath=/live/mytest sound_format=10 sound_type=2 sound_size=1 sound_rate=3 codec_name=AAC 44100 2ch
2019-11-20 19:54:57 4460 [INFO] [rtmp publish] Handle video. id=4BVBJ78W streamPath=/live/mytest frame_type=1 codec_id=7 codec_name=H264 0x0
2019-11-20 19:57:52 4460 [INFO] [rtmp publish] Close stream. id=4BVBJ78W streamPath=/live/mytest streamId=1
2019-11-20 19:57:52 4460 [INFO] [rtmp disconnect] id=4BVBJ78W
```

**Comment by riesentoaster** [comment]
It seems like the rtmp server is not finding a ffmpeg installation.

It looks in `/usr/local/bin/ffmpeg`, where it usually is found under Linux/MacOS. I don't know much about windows but from what I've learned from a quick internet search, you would need to install ffmpeg and add it to your PATH (have a look at this: https://windowsloop.com/install-ffmpeg-windows-10/). The server then would need to be adjusted to check whether it runs on a UNIX or Windows system and change its config accordingly. 

Could you install ffmpeg on your system and comment the directory you put it in? I'll update the server accordingly.

**Comment by riesentoaster** [comment]
So I found [node-ffmpeg-installer](https://www.npmjs.com/package/@ffmpeg-installer/ffmpeg), a package that installs ffmpeg as a node-module. It is a bit clunky but works fine as far as I have seen. And it removes the necessity for the user to add an other installation step. Pull the current repo and try to run the server again please!

**Comment by zubi45** [comment]
Great, I've tried it and it worked from the scratch. Thanks a lot. by the way. I have ffmpeg installed already several times on my machine if you can show me where to change the path, that might also be a solution. 
Next time I would like to try the setup on my raspy. Is there a possibility to write a bash script running on start up, so I don't need to connect display and keyboard on this small machine once it's installed?

**Comment by riesentoaster** [comment]
In the current state of the repo, it is no longer necessary to install ffmpeg by hand.

It is installed as a module, which on one hand is very inefficient and clunky (especially on computers where it is already installed). But it also means that setting up the server requires very little technical knowledge, you don't have to adjust code or anything. As long as you have a very basic understanding of git and your shell (bash, powershell…), you can run this project.

I feel like this is a tradeoff I'd be willing to make per default. If you don't like it, you could still go in and remove the dependency in `package.json`/`package-lock.json` and adjust the path in `src/streamingserver.ts`. If you don't have dire hard drive space constraints I probably wouldn't advise it though.

Regarding the RasPi I have opened a new issue.

**Comment by ahmetugur91** [comment]
> So I found [node-ffmpeg-installer](https://www.npmjs.com/package/@ffmpeg-installer/ffmpeg), a package that installs ffmpeg as a node-module. It is a bit clunky but works fine as far as I have seen. And it removes the necessity for the user to add an other installation step. Pull the current repo and try to run the server again please!

thank you
